### ISSUE TITLE
How does this repo relate to the RHEL7 Systemd RPMs?

### ISSUE THREAD

**Issue by gleventhal** [systemd-rhel/rhel-7#63]
I see in the bugzilla https://bugzilla.redhat.com/show_bug.cgi?id=1770158 that this repo is referenced.  I want to understand how the RHEL systemd development cycle works in relation to github systemd projects.  How does the code in the RHEL RPM systemd-219-67.el7_7.2.src.rpm relate to the systemd projects in github?  Is this Repo used for generating the upstream RHEL systemd RPMs?

**Comment by gleventhal** [comment]
@lnykryn bump?

**Comment by lnykryn** [comment]
In most cases, you can say that this repo is the upstream for RHEL packages. But there might be some exceptions like embargoed CVEs when the code here appears after the package was released. But after a while for every released package, there should be a corresponding tag in this repository (https://github.com/systemd-rhel/rhel-7/releases/tag/v219-67.2 for your example).

But please note that we don't provide any warranties that the code here will actually match the official RHEL content and we don't provide any official support here. If you are Red Hat customer, you should always get through our customer portal, and for centos issues, we still need to have a bug in Red Hat Bugzilla.
