### ISSUE TITLE
mount: access to automounted volumes can lock up

### ISSUE THREAD

**Issue by w-simon** [systemd-rhel/rhel-7#98]
This is a copy of the following issues:
systemd/systemd#15221

We may need to port the following patches to the rhel's systemd to resolve the denial of service failure:
commit ba0d56f （"mount: don't propagate errors from mount_setup_unit() further up"）

Thanks,

**Comment by dtardon** [comment]
@w-simon Please report systemd bugs in Red Hat Enterprise Linux to https://bugzilla.redhat.com .
